// src/entrypoints/options/components/RuleCheckResult.svelte
<script lang="ts">
  import {
    ArrowRightIcon,
    AlertTriangleIcon,
    CheckCircleIcon,
  } from '@lucide/svelte'
  import type { CheckResult } from '$lib/check'
  import * as Alert from '$lib/components/ui/alert'

  interface Props {
    result: CheckResult
  }

  let { result }: Props = $props()
</script>

{#if result.status === 'matched'}
  <Alert.Root variant="default">
    <CheckCircleIcon class="w-4 h-4" />
    <Alert.Description>
      <div class="space-y-2">
        <p class="text-green-600 font-medium">
          Valid redirect chain ({result.urls.length} redirect{result.urls
            .length === 1
            ? ''
            : 's'})
        </p>
        <div class="text-sm text-muted-foreground">
          <p class="font-medium mb-1">Redirect chain:</p>
          <div class="space-y-1">
            {#each result.urls as url, index}
              <div class="flex items-start gap-2">
                <div
                  class="text-xs font-mono bg-muted p-2 rounded flex-1 break-all overflow-hidden"
                >
                  {url}
                </div>
              </div>
            {/each}
          </div>
        </div>
      </div>
    </Alert.Description>
  </Alert.Root>
{:else if result.status === 'not-matched'}
  <Alert.Root variant="default">
    <AlertTriangleIcon class="w-4 h-4" />
    <Alert.Description>
      <p class="text-yellow-600 font-medium">
        Redirect does not match any rules
      </p>
    </Alert.Description>
  </Alert.Root>
{:else if result.status === 'excluded'}
  <Alert.Root variant="default">
    <AlertTriangleIcon class="w-4 h-4" />
    <Alert.Description>
      <p class="text-yellow-600 font-medium">
        Matches the rule, but the exclude pattern blocks the redirect
      </p>
    </Alert.Description>
  </Alert.Root>
{:else if result.status === 'circular-redirect'}
  <Alert.Root variant="destructive">
    <AlertTriangleIcon class="w-4 h-4" />
    <Alert.Description>
      <div class="space-y-2">
        <p class="font-medium">Circular redirect detected!</p>
        <div class="text-sm">
          <p class="font-medium mb-1">Redirect chain:</p>
          <div class="space-y-1">
            {#each result.urls as url, index}
              <div class="flex items-start gap-2">
                <div
                  class="text-xs font-mono bg-muted p-2 rounded flex-1 break-all overflow-hidden {index ===
                  result.urls.length - 1
                    ? 'bg-red-100 border border-red-200'
                    : ''}"
                >
                  {url}
                </div>
              </div>
            {/each}
          </div>
        </div>
      </div>
    </Alert.Description>
  </Alert.Root>
{:else if result.status === 'infinite-redirect'}
  <Alert.Root variant="destructive">
    <AlertTriangleIcon class="w-4 h-4" />
    <Alert.Description>
      <div class="space-y-2">
        <p class="font-medium">Infinite redirect detected!</p>
        <p class="text-sm">
          Too many redirects (>{result.urls.length})
        </p>
        <div class="text-sm">
          <p class="font-medium mb-1">Redirect chain (partial):</p>
          <div class="space-y-1">
            {#each result.urls.slice(0, 3) as url, index}
              <div class="flex items-start gap-2">
                <div
                  class="text-xs font-mono bg-muted p-2 rounded flex-1 break-all overflow-hidden"
                >
                  {url}
                </div>
              </div>
            {/each}
            {#if result.urls.length > 3}
              <div class="text-xs text-muted-foreground text-center py-1">
                ... and {result.urls.length - 3} more redirects
              </div>
            {/if}
          </div>
        </div>
      </div>
    </Alert.Description>
  </Alert.Root>
{/if}

// src/entrypoints/options/components/RuleCheckResult.tsx
import { CircleCheckIcon, TriangleAlertIcon } from "lucide-react";

import type { CheckResult } from "$lib/check";
import { Alert, AlertDescription } from "$lib/components/ui/alert";
import { cn } from "$lib/utils";

interface RuleCheckResultProps {
	result: CheckResult;
}

function UrlChain({
	urls,
	highlightLast = false,
}: {
	urls: string[];
	highlightLast?: boolean;
}) {
	return (
		<div className="space-y-1">
			{urls.map((url, index) => (
				<div key={index} className="flex items-start gap-2">
					<div
						className={cn(
							"bg-muted flex-1 overflow-hidden rounded p-2 font-mono text-xs break-all",
							highlightLast &&
								index === urls.length - 1 &&
								"border border-red-200 bg-red-100",
						)}
					>
						{url}
					</div>
				</div>
			))}
		</div>
	);
}

export default function RuleCheckResult({ result }: RuleCheckResultProps) {
	if (result.status === "matched") {
		return (
			<Alert variant="default">
				<CircleCheckIcon className="h-4 w-4" />
				<AlertDescription>
					<div className="space-y-2">
						<p className="font-medium text-green-600">
							Valid redirect chain ({result.urls.length} redirect
							{result.urls.length === 1 ? "" : "s"})
						</p>
						<div className="text-muted-foreground text-sm">
							<p className="mb-1 font-medium">Redirect chain:</p>
							<UrlChain urls={result.urls} />
						</div>
					</div>
				</AlertDescription>
			</Alert>
		);
	}
	if (result.status === "not-matched") {
		return (
			<Alert variant="default">
				<TriangleAlertIcon className="h-4 w-4" />
				<AlertDescription>
					<p className="font-medium text-yellow-600">
						Redirect does not match any rules
					</p>
				</AlertDescription>
			</Alert>
		);
	}
	if (result.status === "excluded") {
		return (
			<Alert variant="default">
				<TriangleAlertIcon className="h-4 w-4" />
				<AlertDescription>
					<p className="font-medium text-yellow-600">
						Matches the rule, but the exclude pattern blocks the redirect
					</p>
				</AlertDescription>
			</Alert>
		);
	}
	if (result.status === "circular-redirect") {
		return (
			<Alert variant="destructive">
				<TriangleAlertIcon className="h-4 w-4" />
				<AlertDescription>
					<div className="space-y-2">
						<p className="font-medium">Circular redirect detected!</p>
						<div className="text-sm">
							<p className="mb-1 font-medium">Redirect chain:</p>
							<UrlChain urls={result.urls} highlightLast />
						</div>
					</div>
				</AlertDescription>
			</Alert>
		);
	}
	if (result.status === "infinite-redirect") {
		return (
			<Alert variant="destructive">
				<TriangleAlertIcon className="h-4 w-4" />
				<AlertDescription>
					<div className="space-y-2">
						<p className="font-medium">Infinite redirect detected!</p>
						<p className="text-sm">
							Too many redirects (&gt;{result.urls.length})
						</p>
						<div className="text-sm">
							<p className="mb-1 font-medium">Redirect chain (partial):</p>
							<UrlChain urls={result.urls.slice(0, 3)} />
							{result.urls.length > 3 && (
								<div className="text-muted-foreground py-1 text-center text-xs">
									... and {result.urls.length - 3} more redirects
								</div>
							)}
						</div>
					</div>
				</AlertDescription>
			</Alert>
		);
	}
	return null;
}
